# Generated by Django 4.0.3 on 2022-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecurie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=20)),
                ('team_manager', models.CharField(max_length=50)),
                ('sponsor', models.CharField(max_length=20)),
                ('date_creation', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
