# Generated by Django 4.0.3 on 2022-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applimoto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
