# Generated by Django 4.0.3 on 2022-05-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applimoto', '0003_rename_nom_pilote_nom_pilote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilote',
            old_name='nom_pilote',
            new_name='nom',
        ),
    ]
