# Generated by Django 4.0.4 on 2022-05-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applimoto', '0004_rename_nom_pilote_pilote_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilote',
            name='ecurie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applimoto.ecurie'),
        ),
    ]
